php:
    image: php:7-fpm
    volumes:
        - "./code:/var/www/html"
web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - "./code:/var/www/html"
        - "./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        - "./docker-config/logs/nginx:/var/log/nginx"
    links:
        - php